# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto Assign to Project(s)

on:
  push:
    branches: [master]
  pull_request:
    branches: [opened, labeled, master]
  issues:
    types: [opened, labeled]
  #pull_request:
  # types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues and NEW pull requests to CHILD project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: "https://github.com/ospic/docs/projects/1"

      - name: Assign issues and pull requests with `enhancement` label to CHILD project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'enhancement') ||
          contains(github.event.pull_request.labels.*.name, 'enhancement')
        with:
          project: "https://github.com/ospic/docs/projects/1"
          column_name: "To do"
      - name: Assign NEW issues and NEW pull requests to HEADER project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: "https://github.com/orgs/ospic/projects/1"

      - name: Assign issues and pull requests with `enhancement` label to HEADER project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'enhancement') ||
          contains(github.event.pull_request.labels.*.name, 'enhancement')
        with:
          project: "https://github.com/orgs/ospic/projects/1"
          column_name: "To do"

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

        with:
          node-version: ${{ matrix.node-version }}
      - run: npm cache verify
      - name: Install typescript
        run: npm install -D typescript
      - name: Install ts-node
        run: npm install -D ts-node

      - run: npm i --save
      - run: npm run generate

      - name: Deploy to gihub pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
